# -*- coding: utf-8 -*-
"""Nasdaq-100 constituents sorted by market capitalization.

Data refreshed on 2026-06-18 from StockAnalysis.com.
The Nasdaq official index page reported 101 components on 2026-06-17.
"""

NASDAQ100_STOCK_INDEX = {
    "NVDA": "NVIDIA Corporation",
    "GOOGL": "Alphabet Inc.",
    "GOOG": "Alphabet Inc.",
    "AAPL": "Apple Inc.",
    "MSFT": "Microsoft Corporation",
    "AMZN": "Amazon.com, Inc.",
    "AVGO": "Broadcom Inc.",
    "TSLA": "Tesla, Inc.",
    "META": "Meta Platforms, Inc.",
    "MU": "Micron Technology, Inc.",
    "WMT": "Walmart Inc.",
    "AMD": "Advanced Micro Devices, Inc.",
    "ASML": "ASML Holding N.V.",
    "INTC": "Intel Corporation",
    "AMAT": "Applied Materials, Inc.",
    "LRCX": "Lam Research Corporation",
    "CSCO": "Cisco Systems, Inc.",
    "ARM": "Arm Holdings plc",
    "COST": "Costco Wholesale Corporation",
    "NFLX": "Netflix, Inc.",
    "PLTR": "Palantir Technologies Inc.",
    "KLAC": "KLA Corporation",
    "TXN": "Texas Instruments Incorporated",
    "MRVL": "Marvell Technology, Inc.",
    "WDC": "Western Digital Corporation",
    "STX": "Seagate Technology Holdings plc",
    "LIN": "Linde plc",
    "PANW": "Palo Alto Networks, Inc.",
    "QCOM": "QUALCOMM Incorporated",
    "ADI": "Analog Devices, Inc.",
    "TMUS": "T-Mobile US, Inc.",
    "PEP": "PepsiCo, Inc.",
    "AMGN": "Amgen Inc.",
    "CRWD": "CrowdStrike Holdings, Inc.",
    "APP": "AppLovin Corporation",
    "GILD": "Gilead Sciences, Inc.",
    "HON": "Honeywell International Inc.",
    "ISRG": "Intuitive Surgical, Inc.",
    "SHOP": "Shopify Inc.",
    "BKNG": "Booking Holdings Inc.",
    "VRTX": "Vertex Pharmaceuticals Incorporated",
    "SBUX": "Starbucks Corporation",
    "PDD": "PDD Holdings Inc.",
    "CDNS": "Cadence Design Systems, Inc.",
    "FTNT": "Fortinet, Inc.",
    "MAR": "Marriott International, Inc.",
    "CEG": "Constellation Energy Corporation",
    "MNST": "Monster Beverage Corporation",
    "SNPS": "Synopsys, Inc.",
    "ADP": "Automatic Data Processing, Inc.",
    "CSX": "CSX Corporation",
    "ABNB": "Airbnb, Inc.",
    "MELI": "MercadoLibre, Inc.",
    "CMCSA": "Comcast Corporation",
    "DDOG": "Datadog, Inc.",
    "MDLZ": "Mondelez International, Inc.",
    "ADBE": "Adobe Inc.",
    "NXPI": "NXP Semiconductors N.V.",
    "ROST": "Ross Stores, Inc.",
    "INTU": "Intuit Inc.",
    "ORLY": "O'Reilly Automotive, Inc.",
    "DASH": "DoorDash, Inc.",
    "MPWR": "Monolithic Power Systems, Inc.",
    "AEP": "American Electric Power Company, Inc.",
    "CTAS": "Cintas Corporation",
    "WBD": "Warner Bros. Discovery, Inc.",
    "REGN": "Regeneron Pharmaceuticals, Inc.",
    "PCAR": "PACCAR Inc",
    "BKR": "Baker Hughes Company",
    "FANG": "Diamondback Energy, Inc.",
    "FAST": "Fastenal Company",
    "MCHP": "Microchip Technology Incorporated",
    "EA": "Electronic Arts Inc.",
    "FER": "Ferrovial N.V.",
    "XEL": "Xcel Energy Inc.",
    "EXC": "Exelon Corporation",
    "ODFL": "Old Dominion Freight Line, Inc.",
    "CCEP": "Coca-Cola Europacific Partners PLC",
    "IDXX": "IDEXX Laboratories, Inc.",
    "TTWO": "Take-Two Interactive Software, Inc.",
    "KDP": "Keurig Dr Pepper Inc.",
    "MSTR": "Strategy Inc",
    "ADSK": "Autodesk, Inc.",
    "ALNY": "Alnylam Pharmaceuticals, Inc.",
    "PYPL": "PayPal Holdings, Inc.",
    "PAYX": "Paychex, Inc.",
    "TRI": "Thomson Reuters Corporation",
    "AXON": "Axon Enterprise, Inc.",
    "ROP": "Roper Technologies, Inc.",
    "WDAY": "Workday, Inc.",
    "GEHC": "GE HealthCare Technologies Inc.",
    "KHC": "The Kraft Heinz Company",
    "DXCM": "DexCom, Inc.",
    "CPRT": "Copart, Inc.",
    "CTSH": "Cognizant Technology Solutions Corporation",
    "VRSK": "Verisk Analytics, Inc.",
    "TEAM": "Atlassian Corporation",
    "INSM": "Insmed Incorporated",
    "ZS": "Zscaler, Inc.",
    "CHTR": "Charter Communications, Inc.",
    "CSGP": "CoStar Group, Inc.",
}

__all__ = ["NASDAQ100_STOCK_INDEX"]
