export const trendIndicatorDescriptions: Record<string, string> = {
  marketRegime: '市场环境由短周期基准趋势、股票宽度和风险共同决定。Market Score >= 65 为 RISK_ON，< 40 为 RISK_OFF，其余为 NEUTRAL。',
  marketScore: 'Market Score = 0.35×BenchmarkTrend + 0.40×Breadth + 0.25×Risk。BenchmarkTrend = Mean(I(Close>MA10)×100, I(Close>MA20)×100, clamp(50+400R5), clamp(50+300R20))；Breadth = Mean(UpRatio×100, AboveMA10Ratio×100, AboveMA20Ratio×100, clamp(50+200×(High10Count−Low10Count)/ReadyCount))；Risk = Mean(clamp(100−180×Vol20), clamp(100+300×DD20))。',
  marketScoreChange: '所选交易日 Market Score 相对上一可用交易日的变化；正值表示整体市场环境改善。',
  breadthScoreChange: 'Market Score Breakdown 中 Breadth 分相对上一可用交易日的变化；正值表示上涨和站上短周期均线的股票范围扩大。',
  maxExposure: '当前市场环境允许的理论策略总风险敞口上限，不是用户实际仓位。RISK_ON = 100%，NEUTRAL = 50%，RISK_OFF = 20%；RISK_OFF 超限时从 Alpha 最弱持仓开始安排逐单元减仓。',
  universeSize: '当日策略应覆盖的股票总数；A 股为沪深300+中证500，美股为 S&P 500。',
  dataCoverage: '目标交易日日线行情覆盖率，只检查成分股在该日是否存在日线记录。Data Coverage = DataReadyCount / UniverseSize，要求 >= 95%；至少 21 根日线的历史覆盖率在后续 feature/history coverage 阶段单独检查。',
  rankable: '可排名股票数，即通过历史覆盖检查、用至少 21 根日线完成短周期特征计算并进入横截面排名的标的数量。',
  candidate: '当日 CANDIDATE 状态数，不包含观察或持有状态。Candidate = Count(State == "CANDIDATE")；新候选要求 TrendCandidate、Trend >= 62、RS >= 60、ValidSetup、Alpha >= 67 且 Regime != RISK_OFF。TrendCandidate 为 Close>MA10、MA10>MA20、Return10>0、Slope15>0 四项至少满足三项。',
  lifecycleCount: '当日 Snapshot 的动作计数：ENTRY、ADD、HOLD、REDUCE、EXIT 分别按对应 Action 统计；Candidate 另按 State == "CANDIDATE" 统计。',
  rank: 'Alpha Score 的当日横截面排名，1 为最强；同分时按股票代码稳定排序。',
  state: '策略状态表示标的在观察、候选、入场、加仓、持有、弱化、减仓或退出生命周期中的位置。状态转移在收盘生成信号，下一交易日开盘执行。',
  action: '当日公共策略动作，不代表用户真实交易。前一收盘的 pending action 在当日开盘转为 ENTRY/ADD/REDUCE/EXIT；当日收盘只产生下一开盘待执行信号。',
  alpha: 'Alpha = 0.35×Trend + 0.30×RS + 0.20×Breakout + 0.10×VolumeQuality + 0.05×Compression，并 clamp 到 0–100。',
  trend: '短周期趋势分。Trend = clamp(0.30×SlopePercentile15 + 0.20×100R²15 + 0.20×clamp(50+250R10) + 0.20×clamp(50+250R20) + 0.10×clamp(100+250DD20))。',
  relativeStrength: '短周期相对强弱分。RS = clamp(0.25×clamp(50+400RS5) + 0.35×clamp(50+350RS10) + 0.20×clamp(50+300RS20) + 0.10×PctRank(R10) + 0.10×PctRank(R20))。',
  breakout: '短周期 setup 质量分。Breakout = clamp(0.25×DistanceQuality + 0.20×VolumeQuality + 0.20×MA20ExtensionQuality + 0.10×Compression + 0.10×Breakout10Strength + 0.10×Breakout20Strength + 0.05×TrendResume)。ValidSetup 为 false 时 DistanceQuality = 0；否则目标突破距离约为 0.75 ATR。',
  setup: '当日短周期形态：压缩后突破前 10 日高点为 COMPRESSION_BREAKOUT；否则突破前 20 日高点为 BREAKOUT_20D；否则突破前 10 日高点为 BREAKOUT_10D；满足趋势恢复条件时可标记 TREND_RESUME。',
  trendResume: '趋势恢复要求 Close>MA10>MA20、15D slope>0、近 3D 或 5D 收益为正，同时未形成 10D breakout、RS10>0 且 Return10 percentile >= 60。',
  return: '5/10/20 个交易日区间收益率。Return_N = Close[t] / Close[t−N] − 1。',
  atr: '最近 20 日平均真实波幅。TR = max(High−Low, |High−PrevClose|, |Low−PrevClose|)；ATR20 = Mean(TR, 20)。',
  reference: '当日策略快照的收盘参考价；收盘信号不会假设在同一收盘价成交。',
  signal: '收盘产生待执行信号的日期与参考价；实际模拟执行使用下一交易日开盘价。',
  entry: '前一收盘 ENTRY 待执行信号于下一交易日生效后记录的模拟入场日期与开盘价。',
  initialStop: '初始风险线在 2 ATR 止损与有效结构低点止损中取更紧价位。',
  nextAdd: '下一次允许加仓的价格门槛：LastAddPrice + 0.5×SignalATR20，最多累计 4 个策略单元。',
  exitLevel: 'ExitLevel = max(InitialStop, TrailingStop, PreviousLow10)。EXIT 分别按 Close <= InitialStop、Close <= TrailingStop 或 Close < PreviousLow10 判定。',
  initialWeight: '理论初始风险权重使触发初始止损时策略 NAV 理论亏损不超过 0.5%，并受 10% 单股上限约束。',
  reasons: '状态转移或动作的机器可读原因，直接来自策略规则判断。',
  weightedSlope: '最近 15 个收盘价的加权对数趋势斜率，越近权重越高。对 log(Close) 与序号做加权最小二乘回归，权重为 1,2,…,15。',
  slopePercentile: '15D raw weighted slope 在当日可排名股票中的独立横截面百分位；它不是 raw slope 本身。PctRank = AverageZeroBasedPosition / (Count−1) × 100，并列值使用平均位置。',
  r2: '15D 加权趋势拟合度，越接近 1 表示价格越贴合趋势线，本身不区分涨跌方向。',
  drawdown: '20 日窗口内从峰值到后续低点的最大跌幅；负值越接近 0 越好。',
  movingAverage: 'MA10/MA20 用于短周期绝对趋势、弱化和恢复判断；MA_N = Mean(Close, 最近 N 日)。',
  rawRelativeStrength: '相对基准的 5/10/20 日超额收益；RS_N = Stock Return_N − Benchmark Return_N。',
  returnPercentile: '股票 10/20 日收益在当日可排名成分股中的百分位，0 最弱、100 最强；并列值使用平均位置。',
  breakoutFlags: '是否向上突破当日之前 10/20 个交易日的最高价。Breakout_N = Close[t] > Max(High[t−N…t−1])。',
  volumeCompression: 'VolumeRatio 使用当日成交量相对前 20 日均量；压缩要求前 10 日 ATR 不高于前 20 日 ATR 的 80%，且前 10 日价格区间/前 20 日价格区间 <= 60%。',
  units: '当前理论策略单元数，初次入场为 1，每次有效加仓加 1，最多 4 个单元。',
  trailingStop: '只升不降的 ATR 跟踪止损：CandidateTrailing = HighestClose − 2.5×ATR20。',
};
