export const trendIndicatorDescriptions: Record<string, string> = {
  marketRegime: '市场环境，用基准趋势、股票宽度和市场风险限制新开仓敞口。规则：Market Score >= 65 为 RISK_ON，< 40 为 RISK_OFF，其余为 NEUTRAL。',
  marketScore: '市场综合分，越高表示趋势、宽度和风险环境越有利。公式：Market Score = 0.35×BenchmarkTrend + 0.40×Breadth + 0.25×Risk。BenchmarkTrend = Mean(100×I(Close>MA20), 100×I(Close>MA60), clamp(50+300R20), clamp(50+200R60))；Breadth = Mean(UpRatio×100, AboveMA20Ratio×100, AboveMA60Ratio×100, clamp(50+200×(High20Count−Low20Count)/max(ReadyCount, 1)))；Risk = Mean(clamp(100−180×Vol20), clamp(100+300×DD60))。本提示中 clamp(x) = min(100, max(0, x))。',
  maxExposure: '当前市场环境允许的理论策略总风险敞口上限，不是用户实际仓位。映射：RISK_ON = 100%，NEUTRAL = 50%，RISK_OFF = 0%。',
  universeSize: '当日策略应覆盖的股票总数；A 股为沪深300+中证500，美股为 S&P 500。公式：Universe Size = 成分股去重后数量。',
  dataCoverage: '目标交易日日线行情覆盖率，只检查成分股在该日是否存在日线记录，不包含历史长度检查。公式：Data Coverage = DataReadyCount / UniverseSize，要求 >= 95%。至少 61 根日线的历史覆盖率在后续 feature/history coverage 阶段单独检查。',
  rankable: '可排名股票数，即已通过后续历史覆盖检查、用至少 61 根日线完成特征计算，并进入横截面评分与排名的标的数量。',
  candidate: '当日 CANDIDATE 状态数，不包含观察或持有状态。统计：Candidate = Count(State == "CANDIDATE")。新候选规则：TrendCandidate 且 Trend >= 65 且 RS >= 65 且 ValidSetup 且 Alpha >= 70，并且 Regime != RISK_OFF；TrendCandidate 要求 Close > MA20 > MA60 且 MA20 > PreviousMA20。',
  lifecycleCount: '当日 Snapshot 的策略动作计数。统计：ENTRY = Count(Action == "ENTRY")；ADD = Count(Action == "ADD")；HOLD = Count(Action == "HOLD")；REDUCE = Count(Action == "REDUCE")；EXIT = Count(Action == "EXIT")。Candidate 另按 State == "CANDIDATE" 统计。',
  rank: 'Alpha Score 的当日横截面排名，1 为最强；同分时按股票代码稳定排序。',
  state: '策略状态，表示标的在观察、候选、入场、加仓、持有、弱化、减仓或退出生命周期中的位置。状态转移在收盘生成信号，下一交易日开盘执行。',
  action: '当日公共策略动作，不代表用户真实交易。规则：前一收盘的 pending action 在当日开盘转为 ENTRY/ADD/REDUCE/EXIT；当日收盘只会产生下一开盘待执行信号。',
  alpha: '综合 Alpha 分，汇总趋势、相对强弱、突破质量、量能和压缩形态；越高优先级越高。公式：Alpha = 0.35×Trend + 0.30×RS + 0.20×Breakout + 0.10×VolumeQuality + 0.05×Compression，并 clamp 到 0–100；VolumeQuality = clamp((VolumeRatio−0.5)×80)，Compression 在压缩成立时为 100，否则为 0。',
  trend: '趋势分，同时评估对数价格斜率、拟合度、20/60 日收益和 60 日回撤。公式：Trend = clamp(0.30×clamp(SlopePct) + 0.25×clamp(100R²) + 0.20×clamp(50+250R20) + 0.15×clamp(50+125R60) + 0.10×clamp(100+250DD60))，clamp 上下界为 0 和 100。',
  relativeStrength: '相对强弱分，结合相对基准的超额收益和成分股横截面收益排名。公式：RS = clamp(0.30×clamp(50+300×RS20) + 0.20×clamp(50+200×RS60) + 0.30×clamp(PctRank(R20)) + 0.20×clamp(PctRank(R60)))，clamp 上下界为 0 和 100。',
  breakout: '突破质量分，奖励距前高约 0.75 ATR、放量、不过度远离 MA20、前期压缩及 20/55 日突破强度。公式：Breakout = clamp(0.25×DistanceQuality + 0.20×VolumeQuality + 0.20×MA20ExtensionQuality + 0.10×Compression + 0.10×Breakout20Strength + 0.15×Breakout55Strength)。BreakoutDistance = max(0, Close/BaseHigh−1)，55 日突破时 BaseHigh = PreviousHigh55，否则为 PreviousHigh20；无 20/55 日突破时该值为 0。ValidSetup == false 时 DistanceQuality = 0；ValidSetup == true 时 DistanceQuality = clamp(100−55×abs(BreakoutDistance×Close/max(ATR, 1e-12)−0.75))。VolumeQuality = clamp((VolumeRatio−0.5)×80)；MA20ExtensionQuality = clamp(100−800×max(0, max(0, DistanceFromMA20)−8%))；Compression 在 PriorCompression 成立时为 100，否则为 0；BreakoutNStrength = clamp(50×max(0, (Close−PreviousHighN)/max(ATR, 1e-12)))。本式 clamp 上下界为 0 和 100。',
  setup: '当日突破形态。规则：Close>前 55 日最高价为 BREAKOUT_55D；否则前期压缩且 Close>前 20 日最高价为 COMPRESSION_BREAKOUT；否则仅突破前 20 日高点为 BREAKOUT_20D。',
  return: '区间收益率，衡量 20 或 60 个交易日内的价格变化。公式：Return_N = Close[t] / Close[t−N] − 1。',
  atr: '最近 20 日平均真实波幅，以价格单位表示，用于止损和加仓间隔。公式：TR = max(High−Low, |High−PrevClose|, |Low−PrevClose|)；ATR20 = Mean(TR, 20)。',
  reference: '当日策略快照的收盘参考价。公式：Reference Price = Close[t]；收盘信号不会假设在同一收盘价成交。',
  signal: '收盘产生待执行信号的日期与当日收盘价。公式：Signal Price = Reference Price on Signal Date；实际模拟执行使用下一交易日开盘价。',
  entry: '策略模拟入场日期与入场价，只在前一收盘的 ENTRY 待执行信号于下一交易日生效后记录。公式：Entry Price = next-session Open。',
  initialStop: '初始风险线，在 2 ATR 止损与有效结构低点止损中取更紧的价位。公式：ATRStop = Entry−2×SignalATR20；StructureStop = RecentStructureLow−0.5×SignalATR20。仅当 0 < StructureStop < Entry 时 InitialStop = max(ATRStop, StructureStop)，否则 InitialStop = ATRStop；若结果仍不满足 0 < InitialStop < Entry，则使用 max(Entry×1%, min(Entry−1e-8, ATRStop))。',
  nextAdd: '下一次允许加仓的价格门槛，最多累计 4 个策略单元。公式：NextAdd = LastAddPrice + 0.5×SignalATR20；当日收盘达标后于下一开盘执行。',
  exitLevel: '当前综合退出风险线，取初始止损、跟踪止损和前 10 日低点中最高者。展示公式：ExitLevel = max(InitialStop, TrailingStop, PreviousLow10)。实际 EXIT 判定严格按三个条件分别比较：Close <= InitialStop，或 Close <= TrailingStop，或 Close < PreviousLow10；触发后生成下一开盘待执行 EXIT。',
  initialWeight: '单个标的的理论初始风险权重，使触发初始止损时策略 NAV 理论亏损不超过 0.5%，并受 10% 单股上限约束。公式：Weight = min(0.5% / ((Entry−InitialStop)/Entry), 10%)。',
  reasons: '当日状态转移或动作的机器可读原因，直接来自策略规则判断，不是生成式解读。',
  weightedSlope: '最近 25 个收盘价的加权对数趋势斜率，越近的交易日权重越高。公式：对 log(Close) 与序号做加权最小二乘回归，权重为 1,2,…,25；SlopePct = AverageZeroBasedPosition / (Count−1) × 100，并列值使用平均位置，单个标的为 100。',
  r2: '加权趋势拟合度，越接近 1 表示最近 25 日价格越贴合趋势线，本身不区分涨跌。公式：R² = 1 − WeightedResidualSS / WeightedTotalSS。',
  drawdown: '最大回撤，衡量 20/60 日窗口内从峰值到后续低点的最大跌幅；负值越接近 0 越好。公式：MaxDrawdown_N = min(Close[i] / RunningPeak[i] − 1)。',
  movingAverage: '移动平均线，用于判断绝对趋势和弱化。公式：MA_N = Mean(Close, 最近 N 日)；初始候选需 Close>MA20>MA60 且 MA20 高于前一日 MA20。',
  rawRelativeStrength: '相对基准的 20/60 日超额收益；正值表示跑赢基准。公式：RS_N = Stock Return_N − Benchmark Return_N。',
  returnPercentile: '股票 20/60 日收益在当日可排名成分股中的百分位，0 最弱、100 最强；并列值使用平均位置。公式：PctRank = AverageZeroBasedPosition / (Count−1) × 100；仅有一个标的时为 100。',
  breakoutFlags: '是否向上突破当日之前 20/55 个交易日的最高价。公式：Breakout_N = Close[t] > Max(High[t−N…t−1])。',
  volumeCompression: '量能比衡量当日成交量相对前 20 日均量；压缩要求前 20 日 ATR 不高于前 40 日 ATR 的 80%，且前 20 日价格区间/前 60 日价格区间≤60%。公式：VolumeRatio = Volume[t] / Mean(Volume[t−20…t−1])。',
  units: '当前理论策略单元数，初次入场为 1，每次有效加仓加 1，最多 4 个单元。理论持仓权重 = min(Units×InitialWeight, 10%)。',
  trailingStop: '只升不降的 ATR 跟踪止损。公式：CandidateTrailing = HighestClose − 2.5×ATR20；TrailingStop[t] = max(TrailingStop[t−1], CandidateTrailing)。',
};
