export const trendIndicatorDescriptions: Record<string, string> = {
  marketRegime: '市场环境由短周期基准趋势、股票宽度和风险共同决定。Market Score >= 65 为 RISK_ON，< 40 为 RISK_OFF，其余为 NEUTRAL。',
  marketScore: 'Market Score = 0.35×BenchmarkTrend + 0.40×Breadth + 0.25×Risk。BenchmarkTrend = Mean(I(Close>MA10)×100, I(Close>MA20)×100, clamp(50+400R5), clamp(50+300R20))；Breadth = Mean(UpRatio×100, AboveMA10Ratio×100, AboveMA20Ratio×100, clamp(50+200×(High10Count−Low10Count)/max(ReadyCount, 1)))；Risk = Mean(clamp(100−180×Vol20), clamp(100+300×DD20))。',
  marketScoreChange: '所选交易日 Market Score 相对上一可用交易日的变化；正值表示整体市场环境改善。',
  breadthScoreChange: 'Market Score Breakdown 中 Breadth 分相对上一可用交易日的变化；正值表示上涨和站上短周期均线的股票范围扩大。',
  universeSize: '当日策略应覆盖的股票总数；A 股为沪深300+中证500，美股为 S&P 500。',
  dataCoverage: '目标交易日日线行情覆盖率，只检查成分股在该日是否存在日线记录，不包含历史长度检查。Data Coverage = DataReadyCount / UniverseSize，要求 >= 95%；至少 21 根日线的历史覆盖率在后续 feature/history coverage 阶段单独检查。',
  rankable: '可排名股票数，即通过历史覆盖检查、用至少 21 根日线完成短周期特征计算并进入横截面排名的标的数量。',
  candidate: '当日 CANDIDATE 状态数，不包含其他趋势状态。Candidate = Count(State == "CANDIDATE")；新候选要求 TrendCandidate、Trend >= 62、RS >= 60、ValidSetup、Alpha >= 67。TrendCandidate 为 Close>MA10、MA10>MA20、Return10>0、Slope15>0 四项至少满足三项。',
  rankChange: '历史 Alpha Rank − 当前 Alpha Rank，按实际快照交易日偏移 1/3/5 日；正数为上升，缺失显示 —。排序优先 5D，缺失依次使用 3D、1D。',
  rank: 'Alpha Rank 为当前股票池按 Alpha Score 从高到低得到的横截面排名，1 为最高；同分时按股票代码稳定排序。',
  state: '仅描述股票趋势：无明显趋势、形成、候选、健康、弱化、破坏；依据当日指标及前次趋势状态判断。',
  alpha: 'Alpha V2 = 0.40×Trend + 0.25×RS + 0.15×Setup + 0.20×Path。Volume/Compression 仅在 Setup 内计分；旧快照标记 V1。',
  trend: 'Trend = 0.30×SlopePercentile + 0.30×100R² + 0.25×Momentum + 0.15×DrawdownQuality。Momentum = 0.6×Q(R10,0.12)+0.4×Q(R20,0.18)，Q(x,s)=50+50tanh(x/s)；DrawdownQuality=100exp(−|DD20|/0.15)。',
  relativeStrength: 'RS = 0.25×Q(RS5,0.08) + 0.45×Q(RS10,0.12) + 0.30×Q(RS20,0.18)。Q(x,s)=50+50tanh(x/s)；只衡量相对 benchmark 超额收益，不计收益百分位。',
  breakout: 'Setup = 0.50×BreakoutQuality + 0.25×ExtensionQuality + 0.15×VolumeQuality + 0.10×CompressionQuality。BreakoutQuality=max(0.85×B(z10),B(z20))，z=(Close−前高)/ATR20；B(z)=100×sigmoid(z/0.15)×exp(−0.5×((z−0.75)/1)²)。Breakout Score 为 Setup 兼容别名。',
  setup: '当日短周期形态：压缩后突破前 10 日高点为 COMPRESSION_BREAKOUT；否则突破前 20 日高点为 BREAKOUT_20D；否则突破前 10 日高点为 BREAKOUT_10D；满足趋势恢复条件时可标记 TREND_RESUME。',
  trendResume: '趋势恢复要求 Close>MA10>MA20、15D slope>0、近 3D 或 5D 收益为正，同时未形成 10D breakout、RS10>0 且 Return10 percentile >= 60。',
  return: '5/10/20 个交易日区间收益率。Return_N = Close[t] / Close[t−N] − 1。',
  atr: '最近 20 日平均真实波幅。TR = max(High−Low, |High−PrevClose|, |Low−PrevClose|)；ATR20 = Mean(TR, 20)。',
  reference: '当日策略快照的收盘参考价。',
  reasons: '趋势状态的机器可读原因，直接来自策略规则判断。',
  weightedSlope: '对最近 15 个交易日的 log(close) 做加权线性回归，越近的数据权重越高；Slope > 0 表示价格趋势向上。方法：以交易日序号为 x、log(Close) 为 y 做加权最小二乘回归，权重为 1,2,…,15，展示回归直线的日斜率。',
  slopePercentile: 'Weighted Slope 在当日整个股票 Universe 中的横截面百分位排名，100 表示趋势斜率处于当日最强位置；它不是 raw slope 本身。PctRank = AverageZeroBasedPosition / (Count−1) × 100，并列值使用平均位置，Universe 只有一个标的时为 100。',
  r2: '15D 加权趋势拟合度原值，越接近 1 表示价格越贴合趋势线，本身不区分涨跌方向。R² = 1 − WeightedResidualSS / WeightedTotalSS，并限制在 0–1。Alpha 使用 R² Quality = 100×R²。',
  r2Quality: 'Trend 分量：R² Quality = 100×Weighted R²，范围 0–100；旧 V1 快照缺失时显示 —。',
  momentumQuality: 'Trend 分量：Momentum = 0.6×Return10Quality + 0.4×Return20Quality。',
  returnQuality: 'Trend 收益质量分 Q(R,s)=50+50tanh(R/s)；10D 使用 s=0.12，20D 使用 s=0.18。',
  drawdownQuality: 'Trend 分量：DrawdownQuality = 100×exp(−|DD20|/0.15)。',
  rsQuality: 'RS 质量分 Q(RS,s)=50+50tanh(RS/s)；5D/10D/20D 分别使用 0.08/0.12/0.18。',
  drawdown: '20 日窗口内从峰值到后续低点的最大跌幅；负值越接近 0 越好。',
  movingAverage: 'MA10/MA20 用于短周期绝对趋势、弱化和恢复判断；MA_N = Mean(Close, 最近 N 日)。',
  rawRelativeStrength: '相对基准的 5/10/20 日超额收益；RS_N = Stock Return_N − Benchmark Return_N。',
  returnPercentile: '10/20 日收益的横截面百分位，保留用于解释和趋势恢复状态，不再进入 RS 或直接奖励 Alpha。',
  breakoutFlags: '是否向上突破当日之前 10/20 个交易日的最高价。Breakout_N = Close[t] > Max(High[t−N…t−1])。',
  volumeCompression: 'VolumeRatio 使用当日成交量相对前 20 日均量；压缩要求前 10 日 ATR 不高于前 20 日 ATR 的 80%，且前 10 日价格区间/前 20 日价格区间 <= 60%。',
  trendDuration: '当前上升趋势连续成立的交易日数。趋势成立条件：价格高于MA10、MA10高于MA20、10日收益为正、15日加权趋势斜率为正，四个条件至少满足三个。任何一个交易日不再满足趋势条件，持续天数立即归零。',
  path: 'Path = 0.45×ConcentrationQuality + 0.35×VolatilityQuality + 0.20×DownsideControl。Signed Efficiency 仅解释，不计 Alpha。',
  concentration: '最近10日最大的两笔正收益 / 所有正收益之和；≤45%高分，45%–80%用 smoothstep 平滑下降，≥80%低分。无正收益时比值为空、质量分为0。',
  expansion: 'ATR5 / ATR20，包含当日波动。Quality=100exp(−0.5×(max(0,ratio−1.1)/0.8)²)，扩张越强分数越低。',
  downside: '最近10日负收益绝对值均值 / 正收益均值。Quality=100exp(−ratio)，回调相对推动越小越好。没有负收益时100分；没有正收益时比值为空、0分。',
};
