# -*- coding: utf-8 -*-
"""Score-based rule evaluation for US intraday signal candidates."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable, Dict, List, Optional, Sequence, Tuple

from finance_analysis.integrations.market_data.realtime_types import safe_float

from .config import (
    RELATIVE_STRENGTH_BREAKOUT_RULE,
    RELATIVE_STRENGTH_FAILURE_RULE,
    WEAK_TO_STRONG_REVERSAL_RULE,
)

Metrics = Dict[str, Any]
Candidate = Dict[str, Any]
RuleEvaluator = Callable[[Metrics], Tuple[Optional[Candidate], List[str]]]
RulePredicate = Callable[[Metrics], bool]

RULE_VERSION = "v2"


@dataclass
class SignalRule:
    """Pair a signal type with a scoring evaluator."""

    signal_type: str
    evaluate: RuleEvaluator

    def __call__(self, metrics: Metrics) -> bool:
        candidate, _ = self.evaluate(metrics)
        return candidate is not None


def evaluate_signal_candidates(
    metrics: Metrics,
    rules: Optional[Sequence[SignalRule | RulePredicate]] = None,
) -> List[Candidate]:
    """Return candidates generated by the configured rules."""
    candidates, _ = evaluate_signal_candidates_with_diagnostics(metrics, rules)
    return candidates


def evaluate_signal_candidates_with_diagnostics(
    metrics: Metrics,
    rules: Optional[Sequence[SignalRule | RulePredicate]] = None,
) -> Tuple[List[Candidate], List[str]]:
    """Return rule candidates plus failed condition keys for funnel metrics."""
    active_rules = DEFAULT_INTRADAY_SIGNAL_RULES if rules is None else rules
    candidates: List[Candidate] = []
    failed_keys: List[str] = []

    for rule in active_rules:
        if isinstance(rule, SignalRule):
            candidate, failures = rule.evaluate(metrics)
            failed_keys.extend(failures)
            if candidate is not None:
                candidates.append(candidate)
            continue

        if rule(metrics):
            candidates.append(
                {
                    "signal_type": _signal_type_of(rule),
                    "score": 1.0,
                    "max_score": 1.0,
                    "matched_conditions": ["custom_rule"],
                    "failed_conditions": [],
                    "rule_version": RULE_VERSION,
                    "rule_strength": "normal",
                    "severity": "medium",
                }
            )

    return candidates, failed_keys


def _signal_type_of(rule: RulePredicate) -> str:
    signal_type = getattr(rule, "signal_type", None)
    if signal_type:
        return str(signal_type)
    return getattr(rule, "__name__", "custom_signal")


def evaluate_relative_strength_breakout(metrics: Metrics) -> Tuple[Optional[Candidate], List[str]]:
    normal = RELATIVE_STRENGTH_BREAKOUT_RULE["normal"]
    strong = RELATIVE_STRENGTH_BREAKOUT_RULE["strong"]
    required = [_condition("vwap_position", bool(metrics.get("price_above_vwap")), "price_above_vwap")]
    scored = [
        _condition("change_5m", _gte(metrics.get("change_5m"), normal["change_5m_min"]), "change_5m>=0.35"),
        _condition("change_15m", _gte(metrics.get("change_15m"), normal["change_15m_min"]), "change_15m>=0.8"),
        _condition(
            "relative_to_qqq",
            _gte(metrics.get("relative_to_qqq_15m"), normal["relative_to_qqq_15m_min"]),
            "relative_to_qqq_15m>=0.35",
        ),
        _condition(
            "volume_ratio",
            _gte(metrics.get("volume_ratio_5m"), normal["volume_ratio_5m_min"]),
            "volume_ratio_5m>=1.3",
        ),
        _condition(
            "near_high",
            bool(metrics.get("near_intraday_high")) or _lte(metrics.get("high_distance_pct"), normal["near_high_pct"]),
            "high_distance_pct<=0.8",
        ),
    ]
    score = float(sum(1 for item in scored if item.matched))
    failures = [item.key for item in required + scored if not item.matched]
    if not all(item.matched for item in required) or score < float(normal["min_score"]):
        return None, failures

    is_strong = (
        _gte(metrics.get("change_5m"), strong["change_5m_min"])
        and _gte(metrics.get("change_15m"), strong["change_15m_min"])
        and _gte(metrics.get("relative_to_qqq_15m"), strong["relative_to_qqq_15m_min"])
        and _gte(metrics.get("volume_ratio_5m"), strong["volume_ratio_5m_min"])
        and bool(metrics.get("price_above_vwap"))
        and (
            bool(metrics.get("near_intraday_high"))
            or _lte(metrics.get("high_distance_pct"), strong["near_high_pct"])
        )
    )
    return _candidate("relative_strength_breakout", score, scored, failures, is_strong), failures


def evaluate_weak_to_strong_reversal(metrics: Metrics) -> Tuple[Optional[Candidate], List[str]]:
    normal = WEAK_TO_STRONG_REVERSAL_RULE["normal"]
    required = [_condition("vwap_position", bool(metrics.get("price_above_vwap")), "price_above_vwap")]
    scored = [
        _condition(
            "early_relative_strength",
            _lte(metrics.get("early_relative_to_qqq"), normal["early_relative_to_qqq_max"]),
            "early_relative_to_qqq<=-0.2",
        ),
        _condition(
            "relative_to_qqq",
            _gte(metrics.get("relative_to_qqq_15m"), normal["relative_to_qqq_15m_min"]),
            "relative_to_qqq_15m>=0.1",
        ),
        _condition("change_15m", _gte(metrics.get("change_15m"), normal["change_15m_min"]), "change_15m>=0.5"),
        _condition(
            "vwap_position",
            bool(metrics.get("crossed_above_vwap") or metrics.get("last_two_above_vwap")),
            "crossed_or_two_closes_above_vwap",
        ),
        _condition(
            "volume_ratio",
            _gte(metrics.get("volume_ratio_5m"), normal["volume_ratio_5m_min"]),
            "volume_ratio_5m>=1.3",
        ),
    ]
    score = float(sum(1 for item in scored if item.matched))
    failures = [item.key for item in required + scored if not item.matched]
    if not all(item.matched for item in required) or score < float(normal["min_score"]):
        return None, failures
    return _candidate(
        "weak_to_strong_reversal",
        score,
        scored,
        failures,
        is_weak_to_strong_reversal(metrics),
    ), failures


def evaluate_relative_strength_failure(metrics: Metrics) -> Tuple[Optional[Candidate], List[str]]:
    normal = RELATIVE_STRENGTH_FAILURE_RULE["normal"]
    required = [_condition("vwap_position", bool(metrics.get("price_below_vwap")), "price_below_vwap")]
    scored = [
        _condition(
            "early_relative_strength",
            _gte(metrics.get("early_relative_to_qqq"), normal["early_relative_to_qqq_min"]),
            "early_relative_to_qqq>=0.3",
        ),
        _condition(
            "relative_to_qqq",
            _lte(metrics.get("relative_to_qqq_15m"), normal["relative_to_qqq_15m_max"]),
            "relative_to_qqq_15m<=-0.1",
        ),
        _condition("change_5m", _lte(metrics.get("change_5m"), normal["change_5m_max"]), "change_5m<=-0.4"),
        _condition(
            "vwap_position",
            bool(metrics.get("crossed_below_vwap") or metrics.get("last_two_below_vwap")),
            "crossed_or_two_closes_below_vwap",
        ),
        _condition(
            "volume_ratio",
            _gte(metrics.get("volume_ratio_5m"), normal["volume_ratio_5m_min"]),
            "volume_ratio_5m>=1.3",
        ),
    ]
    score = float(sum(1 for item in scored if item.matched))
    failures = [item.key for item in required + scored if not item.matched]
    if not all(item.matched for item in required) or score < float(normal["min_score"]):
        return None, failures
    return _candidate(
        "relative_strength_failure",
        score,
        scored,
        failures,
        is_relative_strength_failure(metrics),
    ), failures


def is_relative_strength_breakout(metrics: Metrics) -> bool:
    strong = RELATIVE_STRENGTH_BREAKOUT_RULE["strong"]
    return (
        _gte(metrics.get("change_5m"), strong["change_5m_min"])
        and _gte(metrics.get("change_15m"), strong["change_15m_min"])
        and _gte(metrics.get("relative_to_qqq_15m"), strong["relative_to_qqq_15m_min"])
        and _gte(metrics.get("volume_ratio_5m"), strong["volume_ratio_5m_min"])
        and bool(metrics.get("price_above_vwap"))
        and (
            bool(metrics.get("near_intraday_high"))
            or _lte(metrics.get("high_distance_pct"), strong["near_high_pct"])
        )
    )


def is_weak_to_strong_reversal(metrics: Metrics) -> bool:
    strong = WEAK_TO_STRONG_REVERSAL_RULE["strong"]
    return (
        _lte(metrics.get("early_relative_to_qqq"), strong["early_relative_to_qqq_max"])
        and _gte(metrics.get("relative_to_qqq_15m"), strong["relative_to_qqq_15m_min"])
        and bool(metrics.get("crossed_above_vwap"))
        and _gte(metrics.get("change_15m"), strong["change_15m_min"])
        and _gte(metrics.get("volume_ratio_5m"), strong["volume_ratio_5m_min"])
    )


def is_relative_strength_failure(metrics: Metrics) -> bool:
    strong = RELATIVE_STRENGTH_FAILURE_RULE["strong"]
    return (
        _gte(metrics.get("early_relative_to_qqq"), strong["early_relative_to_qqq_min"])
        and _lte(metrics.get("relative_to_qqq_15m"), strong["relative_to_qqq_15m_max"])
        and bool(metrics.get("price_below_vwap"))
        and _lte(metrics.get("change_5m"), strong["change_5m_max"])
        and _gte(metrics.get("volume_ratio_5m"), strong["volume_ratio_5m_min"])
    )


@dataclass(frozen=True)
class _ConditionResult:
    key: str
    label: str
    matched: bool


def _condition(key: str, matched: bool, label: str) -> _ConditionResult:
    return _ConditionResult(key=key, label=label, matched=bool(matched))


def _candidate(
    signal_type: str,
    score: float,
    scored: Sequence[_ConditionResult],
    failures: Sequence[str],
    strong: bool,
) -> Candidate:
    return {
        "signal_type": signal_type,
        "score": score,
        "max_score": float(len(scored)),
        "matched_conditions": [item.label for item in scored if item.matched],
        "failed_conditions": [item.label for item in scored if not item.matched],
        "failed_condition_keys": list(failures),
        "rule_version": RULE_VERSION,
        "severity": "high" if strong else "medium",
        "rule_strength": "strong" if strong else "normal",
    }


DEFAULT_INTRADAY_SIGNAL_RULES: List[SignalRule] = [
    SignalRule("relative_strength_breakout", evaluate_relative_strength_breakout),
    SignalRule("weak_to_strong_reversal", evaluate_weak_to_strong_reversal),
    SignalRule("relative_strength_failure", evaluate_relative_strength_failure),
]


def _gte(value: Any, threshold: float) -> bool:
    parsed = safe_float(value)
    return bool(parsed is not None and parsed >= threshold)


def _lte(value: Any, threshold: float) -> bool:
    parsed = safe_float(value)
    return bool(parsed is not None and parsed <= threshold)
