export const indicatorDescriptions: Record<string, string> = {
  return: '区间收益率公式：Return_N = Close[t] / Close[t−N] − 1。只使用 T 日及以前收盘价。',
  composite: '公式：Composite = 0.30×Momentum + 0.25×Relative Strength + 0.25×Acceleration + 0.15×Trend Quality + 0.05×Efficiency。风险指标不参与排名。',
  momentum: '公式：Momentum = 0.30×Rank(Return3) + 0.35×Rank(Return5) + 0.25×Rank(Return10) + 0.10×Rank(Return20)。Rank 是 ETF Universe 横截面百分位，100 最强。',
  trendQuality: '原始公式：TrendQuality15 = AnnualizedSlope15 × R²15；页面分数为该原始值的 ETF Universe 横截面百分位。',
  weightedSlope: '公式：对 log(Close) 关于交易日序号做加权最小二乘回归，样本权重由最早 1 线性升至最新 2。AnnualizedSlope = exp(252×Slope)−1。',
  r2: '公式：R²15 = 1 − 加权残差平方和 / 加权总平方和。越接近 1，最近 15 日价格越贴合趋势线；本身不区分方向。',
  efficiency: '公式：SignedER10 = (Close[t]−Close[t−10]) / Σ|Close[i]−Close[i−1]|。页面分数为横截面百分位；+1 接近单边上涨，−1 接近单边下跌。',
  relativeStrength: '公式：RS_N = ETF Return_N − Benchmark Return_N；Score_N = clamp(50 + 50×RS_N/Range_N, 0, 100)。5/10/20 日 Range 为 5%/8%/12%，最终 RS = 40%×RS5 + 40%×RS10 + 20%×RS20。',
  acceleration: '公式：Acc3 = Return[t−3,t]−Return[t−6,t−3]；Acc5 = Return[t−5,t]−Return[t−10,t−5]；TrendAcc = AnnualizedSlope5−AnnualizedSlope15；最终分数 = 40%×Rank(Acc3)+35%×Rank(Acc5)+25%×Rank(TrendAcc)。',
  volatility: '公式：RealizedVol20 = 最近 20 个日收益的样本标准差 × √252。越高表示价格波动更剧烈；不参与 Composite。',
  drawdown: '公式：MaxDrawdown20 = min(Close / 截至当日的区间峰值 − 1)。以负数表示，越接近 0 回撤越小；不参与 Composite。',
  maDeviation: '公式：MA_N Deviation = Close[t] / Mean(Close 最近 N 日) − 1。MA10 用于快速趋势门槛，MA20 只用于追高惩罚。',
  distanceHigh: '公式：DistanceFromHigh20 = Close[t] / Max(Close 最近 20 日) − 1。越接近 0 表示越接近阶段高点。',
  volumeRatio: '公式：VolumeRatio = 最近 5 日平均成交量 / 最近 20 日平均成交量。≥1.2 时 Entry Score 加 2 分。',
  rankChange: '公式：RankChange_N = N 个历史快照前的 Composite Rank − 当前 Composite Rank。正数表示排名上升，负数表示下降。',
  breadth: '公式：Positive5D Breadth = Count(Return5>0)/Universe；AboveMA10 Breadth = Count(MA10 Deviation>0)/Universe。',
  regime: '公式：两项 Breadth 均≥55%、基准 Return5>0 且 Slope10>0 为 RISK_ON；两项均≤30%、基准 Return5<0 且 Slope10<0 为 RISK_OFF；其余 NEUTRAL。Regime 只控制候选数量。',
  state: '优先级：EXHAUSTED > COOLING > EMERGING > STRONG > TRENDING > WEAK > NEUTRAL。EMERGING 要求 RankΔ3≥5、Acceleration≥70、RS10≥60、Slope10>0 且趋势门槛通过；STRONG 要求 Composite≥75、Trend Quality≥65；TRENDING 要求 Composite≥60。',
  action: 'BUY：Top4、Entry≥70 且状态为 EMERGING/STRONG/TRENDING。HOLD：Top6、Composite≥60，且 Acceleration≥40 或 Return5>0。任一快速衰退条件触发 EXIT。',
  entry: '公式：Entry = clamp(Composite + 温和上涨确认 + 放量确认 − MA20 过度偏离惩罚 − 单日暴涨惩罚, 0, 100)。BUY 阈值为 70。',
  stop: '公式：StopPct = clamp(2.5×RealizedVol20/√252, 3%, 8%)；SuggestedStop = SnapshotClose×(1−StopPct)。仅作公共风险参考。',
};
