export const indicatorDescriptions: Record<string, string> = {
  return: '区间收益率，衡量 ETF 在指定交易日窗口内的涨跌幅；越高表示该窗口动量越强。公式：Return_N = Close[t] / Close[t−N] − 1，只使用 t 日及以前收盘价。',
  composite: '综合轮动分，汇总动量、相对强弱、加速度、趋势质量和效率；越高表示当前强势越全面。公式：Composite = 0.30×Momentum + 0.25×Relative Strength + 0.25×Acceleration + 0.15×Trend Quality + 0.05×Efficiency，各因子均为 0–100 分，风险指标不参与。',
  momentum: '动量强度分，比较 ETF 多个短周期收益在当日可排名 ETF 中的位置；100 最强。公式：Momentum = 0.30×PctRank(Return3) + 0.35×PctRank(Return5) + 0.25×PctRank(Return10) + 0.10×PctRank(Return20)。',
  trendQuality: '趋势质量分，同时奖励上涨速度和趋势线拟合稳定性；页面显示其横截面百分位。原始公式：TrendQuality15 = AnnualizedSlope15 × R²15；Score = PctRank(TrendQuality15)。',
  weightedSlope: '加权对数趋势斜率，近期价格权重更高；正值代表向上，负值代表向下。公式：对 log(Close) 与交易日序号做加权最小二乘回归，权重由最早 1 线性升至最新 2；AnnualizedSlope = exp(clamp(252×Slope, −20, 20)) − 1。',
  r2: '趋势拟合度，表示最近 15 个收盘价对加权趋势线的贴合程度；越接近 1 越稳定，本身不区分涨跌方向。公式：R²15 = 1 − 加权残差平方和 / 加权总平方和。',
  efficiency: '有符号趋势效率，比较 10 日净移动与逐日路径总波动；+1 接近单边上涨，−1 接近单边下跌，页面分数为横截面百分位。公式：SignedER10 = (Close[t]−Close[t−10]) / Σ|Close[i]−Close[i−1]|。',
  relativeStrength: '相对强弱分，衡量 ETF 相对同市场基准的超额收益；50 约等于基准，越高代表跑赢越多。公式：RS_N = ETF Return_N − Benchmark Return_N；Score_N = clamp(50 + 50×RS_N/Range_N, 0, 100)，5/10/20 日 Range = 5%/8%/12%；最终分 = 0.4×Score5 + 0.4×Score10 + 0.2×Score20。',
  acceleration: '动量加速度分，观察近期收益和趋势速度是否比前一阶段增强。公式：Acc3 = Return[t−3,t] − Return[t−6,t−3]；Acc5 = Return[t−5,t] − Return[t−10,t−5]；TrendAcc = AnnualizedSlope5 − AnnualizedSlope15；Score = 0.40×PctRank(Acc3) + 0.35×PctRank(Acc5) + 0.25×PctRank(TrendAcc)。',
  volatility: '实现波动率，衡量最近 20 个日收益的年化波动；越高表示价格波动更剧烈，不参与 Composite。公式：RealizedVol20 = SampleStdDev(DailyReturn, 20) × √252。',
  drawdown: '最大回撤，衡量最近 20 个交易日区间从峰值到后续低点的最大跌幅；以负数表示，越接近 0 回撤越小，不参与 Composite。公式：在最近 21 个收盘价上计算 MaxDrawdown20 = min(Close[i] / RunningPeak[i] − 1)。',
  maDeviation: '均线偏离，衡量当前收盘价与均线的距离；正值表示位于均线上方。公式：MA_N Deviation = Close[t] / Mean(Close, 最近 N 日) − 1；MA10 用于绝对趋势门槛，MA20 用于追高惩罚。',
  distanceHigh: '距 20 日高点，衡量当前收盘价距近 20 日最高收盘价的幅度；越接近 0 越接近阶段高点。公式：DistanceFromHigh20 = Close[t] / Max(Close, 最近 20 日) − 1。',
  volumeRatio: '成交量比，衡量近 5 日相对近 20 日的成交活跃度；大于 1 代表近期放量。公式：VolumeRatio5 = Mean(Volume, 5) / Mean(Volume, 20)；≥1.2 时 Entry 加 2 分。',
  rankChange: '排名变化，衡量 Composite 排名相对历史快照的升降；正数表示排名提升。公式：RankChange_N = 前 N 个交易日快照的 Composite Rank − 当前 Composite Rank。',
  breadth: '市场宽度，衡量强势是否覆盖大多数当日可排名 ETF。公式：Positive5D Breadth = Count(Return5>0) / RankableCount；AboveMA10 Breadth = Count(MA10 Deviation>0) / RankableCount。',
  regime: '市场环境，结合 ETF 宽度与基准短期趋势，只控制新候选数，不改写 ETF 分数。规则：两项 Breadth≥55%、Benchmark Return5>0 且 Slope10>0 为 RISK_ON；两项 Breadth≤30%、Benchmark Return5<0 且 Slope10<0 为 RISK_OFF；其余为 NEUTRAL。',
  benchmark: '市场基准，A 股使用 510300.SH，美股使用 SPY.US；用于计算相对强弱和市场环境，本身不进入 Composite。',
  benchmarkTrend: '基准短期趋势。规则：Return5>0 且 WeightedSlope10>0 为 POSITIVE；两者都<0 为 NEGATIVE；其余为 MIXED。',
  state: '轮动状态，按固定优先级识别过热、降温、初起、强势等阶段。规则优先级：EXHAUSTED > COOLING > EMERGING > STRONG > TRENDING > WEAK > NEUTRAL；例如 EMERGING 要求 RankΔ3≥5、Acceleration≥70、RS10 Score≥60、Slope10>0 且绝对趋势通过。',
  action: '公共轮动信号，只比较当前与上一公开快照，不读取用户持仓。规则：新入选者为 BUY；上日已入选且仍通过 Top6、Composite≥60 及衰退门槛者为 HOLD；上日入选但当日落选者为 EXIT；其他通过硬门槛且 Composite≥55 者为 WATCH。',
  candidate: '候选排名，先保留有效 HOLD，再按 Composite、Rank、代码补充新 BUY。新入选需 Rank≤4、Entry≥70、状态为 EMERGING/STRONG/TRENDING，并通过趋势、流动性、risk group 和 20 日相关性约束。',
  entry: '入场质量分，在 Composite 上奖励温和上涨和放量，惩罚均线过度偏离与单日暴涨。公式：Entry = clamp(Composite + 2×I(0<Return1≤4%) + 2×I(VolumeRatio≥1.2) + MA20Penalty − 5×I(Return1>6%), 0, 100)；MA20 偏离≥5%/10%/15% 时分别取 −2/−5/−10 分，BUY 阈值为 70。',
  absoluteTrend: '绝对趋势门槛，防止仅因“跌得比基准少”而入选。规则：Return5>0、WeightedSlope10>0、MA10 Deviation>0 三项中至少满足两项。',
  liquidity: '流动性门槛，用最近 20 日平均成交额过滤难以执行的标的。公式：AvgAmount20 = Mean(Amount, 20)；A 股需≥5,000 万元，美股需≥500 万美元。',
  stop: '建议止损参考，按 20 日年化波动率换算日波动后设定，不基于个人成本价。公式：StopPct = clamp(2.5×RealizedVol20/√252, 3%, 8%)；SuggestedStop = SnapshotClose×(1−StopPct)。',
};
